### ISSUE TITLE
After creating an app while click overview or creating another app got this error

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/megam_gateway#298]
RUN_NOW Megam::Components.show 
App 4959 stdout: --> (/components/COM1296858863697526784)
App 4959 stdout: 
App 4959 stdout: [2016-01-07T18:12:24+05:30] DEBUG: START
App 4959 stdout: [2016-01-07T18:12:24+05:30] DEBUG: > expects: 200
App 4959 stdout: [2016-01-07T18:12:24+05:30] DEBUG: > method: get
App 4959 stdout: [2016-01-07T18:12:24+05:30] DEBUG: > body: 
App 4959 stdout: [2016-01-07T18:12:24+05:30] DEBUG: HTTP Request Data:
App 4959 stdout: [2016-01-07T18:12:24+05:30] DEBUG: > HTTP http://103.56.92.7
App 4959 stdout: [2016-01-07T18:12:24+05:30] DEBUG: > path: /v2/components/COM1296858863697526784
App 4959 stdout: [2016-01-07T18:12:24+05:30] DEBUG: > body: 
App 4959 stdout: [2016-01-07T18:12:24+05:30] DEBUG: > headers: {"Accept"=>"application/json", "Accept-Encoding"=>"gzip", "User-Agent"=>"megam-api/0.91", "X-Ruby-Version"=>"2.2.2", "X-Ruby-Platform"=>"x86_64-linux", "X-Megam-HMAC"=>"v@mp.com:96efa1da30c6b6b710353c26a49d991d188c7ac9", "X-Megam-DATE"=>"2016-01-07 18:12"}
App 4959 stdout: [2016-01-07T18:12:24+05:30] DEBUG: > host: 103.56.92.7
App 4959 stdout: [2016-01-07T18:12:24+05:30] DEBUG: > nonblock: false
App 4959 stdout: [2016-01-07T18:12:24+05:30] DEBUG: > scheme: http
App 4959 stdout: [2016-01-07T18:12:24+05:30] DEBUG: End HTTP Request Data.
App 4959 stdout: [2016-01-07T18:12:24+05:30] DEBUG: {
App 4959 stdout:   "code":400,
App 4959 stdout:   "msg_type":"error",
App 4959 stdout:   "msg":"Body received from the api contains invalid input. 'body:' \n'{\"id\":\"COM1296858863697526784\",\"name\":\"farted\",\"tosca_type\":\"tosca.app.rails\",\"inputs\":[{\"key\":\"domain\",\"value\":\"megambox.com\"},{\"key\":\"sshkey\",\"value\":\"v@mp.com_mpvs\"},{\"key\":\"provider\",\"value\":\"one\"},{\"key\":\"cpu\",\"value\":\"0.5\"},{\"key\":\"ram\",\"value\":\"896\"},{\"key\":\"version\",\"value\":\"4.x\"},{\"key\":\"lastsuccessstatusupdate\",\"value\":\"2016-01-07 12:24:21.579856721 +0000 UTC\"},{\"key\":\"status\",\"value\":\"deploying\"},{\"key\":\"lastsuccessstatusupdate\",\"value\":\"2016-01-07 12:24:21.751588668 +0000 UTC\"},{\"key\":\"status\",\"value\":\"creating\"}],\"outputs\":[],\"envs\":[{\"key\":\"host\",\"value\":\"localhost\"},{\"key\":\"port\",\"value\":\"8080\"}],\"repo\":{\"rtype\":\"source\",\"source\":\"github\",\"oneclick\":\"\",\"url\":\"https://github.com/vijaykanthm28/nilavu.git\"},\"artifacts\":{\"artifact_type\":\"\",\"content\":\"\",\"requirements\":[]},\"related_components\":[],\"operations\":[{\"operation_type\":\"CI\",\"description\":\"always up to date code. sweet.\",\"properties\":[{\"key\":\"type\",\"value\":\"github\"},{\"key\":\"token\",\"value\":\"9fe52f81d0f206fffb746f6b273105b500f1eb16\"},{\"key\":\"username\",\"value\":\"vijaykanthm28\"}]}],\"status\":\"creating\",\"created_at\":\"2016-01-07 12:24:21 +0000\"}'\nverify the body content as needed for this resource.\n",
App 4959 stdout:   "more":"The error received when parsing the JSON is :\nNo usable value for operations\nNo usable value for status\nDid not find value which can be converted into java.lang.String",
App 4959 stdout:   "json_claz":"Megam::Error",
App 4959 stdout:   "links":"Forum   :http://docs.megam.io/discuss\nDocs    :http://docs.megam.io\nSupport :http://support.megam.io"
App 4959 stdout: }
App 4959 stdout: [2016-01-07T18:12:24+05:30] DEBUG: RESPONSE ERR: Ruby Object
App 4959 stdout: [2016-01-07T18:12:24+05:30] DEBUG: json_claz      =Megam::Error
App 4959 stdout: some_msg       ={:code=>400, :msg_type=>"error", :msg=>"Body received from the api contains invalid input. 'body:' \n'{\"id\":\"COM1296858863697526784\",\"name\":\"farted\",\"tosca_type\":\"tosca.app.rails\",\"inputs\":[{\"key\":\"domain\",\"value\":\"megambox.com\"},{\"key\":\"sshkey\",\"value\":\"v@mp.com_mpvs\"},{\"key\":\"provider\",\"value\":\"one\"},{\"key\":\"cpu\",\"value\":\"0.5\"},{\"key\":\"ram\",\"value\":\"896\"},{\"key\":\"version\",\"value\":\"4.x\"},{\"key\":\"lastsuccessstatusupdate\",\"value\":\"2016-01-07 12:24:21.579856721 +0000 UTC\"},{\"key\":\"status\",\"value\":\"deploying\"},{\"key\":\"lastsuccessstatusupdate\",\"value\":\"2016-01-07 12:24:21.751588668 +0000 UTC\"},{\"key\":\"status\",\"value\":\"creating\"}],\"outputs\":[],\"envs\":[{\"key\":\"host\",\"value\":\"localhost\"},{\"key\":\"port\",\"value\":\"8080\"}],\"repo\":{\"rtype\":\"source\",\"source\":\"github\",\"oneclick\":\"\",\"url\":\"https://github.com/vijaykanthm28/nilavu.git\"},\"artifacts\":{\"artifact_type\":\"\",\"content\":\"\",\"requirements\":[]},\"related_components\":[],\"operations\":[{\"operation_type\":\"CI\",\"description\":\"always up to date code. sweet.\",\"properties\":[{\"key\":\"type\",\"value\":\"github\"},{\"key\":\"token\",\"value\":\"9fe52f81d0f206fffb746f6b273105b500f1eb16\"},{\"key\":\"username\",\"value\":\"vijaykanthm28\"}]}],\"status\":\"creating\",\"created_at\":\"2016-01-07 12:24:21 +0000\"}'\nverify the body content as needed for this resource.\n", :links=>"Forum   :http://docs.megam.io/discuss\nDocs    :http://docs.megam.io\nSupport :http://support.megam.io"}
undefined method `[]' for nil:NilClass
components.rb:26:in`show'
assembly.rb:64:in `block (2 levels) in dig_components'
assembly.rb:62:in`map'
assembly.rb:62:in `block in dig_components'
assembly.rb:61:in`map'
assembly.rb:61:in `dig_components'
assembly.rb:36:in`show'
assemblies.rb:97:in `block (2 levels) in dig_assembly'
assemblies.rb:95:in`map'
assemblies.rb:95:in `block in dig_assembly'
assemblies.rb:94:in`map'
assemblies.rb:94:in `dig_assembly'
assemblies.rb:64:in`list'
cockpits_controller.rb:30:in `index'
application_controller.rb:73:in`catch_exceptions'

**Comment by vijaykanthm28** [comment]
#298 riak updated in megamd
issue fixed.
