### ISSUE TITLE
createhook request failed for 500 error

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/megam_gateway#308]
<div class="page-header">
<h2>Stacktrace</h2>
</div>

<div class="">
<pre><code class="brush: bash; toolbar: false; ">java.util.NoSuchElementException: None.get
    at scala.None$.get(Option.scala:347)
    at scala.None$.get(Option.scala:345)
    at controllers.funnel.FunnelRequestBuilder.funneled(FunnelRequest.scala:105)
    at controllers.stack.SecurityActions$.Authenticated(SecurityActions.scala:48)
    at controllers.stack.APIAuthElement$class.proceed(APIAuthElement.scala:54)
    at controllers.camp.Assembly$.proceed(Assembly.scala:29)
    at jp.t2v.lab.play2.stackc.StackableController$StackActionBuilder.invokeBlock(StackableController.scala:16)
    at jp.t2v.lab.play2.stackc.StackableController$StackActionBuilder.invokeBlock(StackableController.scala:12)
    at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:493)
    at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105)
    at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105)
    at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
    at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:104)
    at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:103)
    at scala.Option.map(Option.scala:146)
    at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:103)
    at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:96)
    at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524)
    at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524)
    at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560)
    at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560)
    at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:537)
    at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:537)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:399)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
</code></pre>
</div>

</div>
</div>

**Comment by vijaykanthm28** [comment]
====> api.megam.io/v2/assembly/upgrade/ASM1304160728042831872 
[debug] application - HEAD: ArrayBuffer((Host,api.megam.io), (X-Real-IP,173.245.54.14), (X-Forwarded-Proto,https), (X-Forwarded-Ssl,on), (X-Forwarded-For,192.30.252.46, 173.245.54.14), (Connection,close), (Content-Length,7039), (Accept-Encoding,gzip), (CF-IPCountry,US), (CF-RAY,26b5ae5c27de246e-IAD), (CF-Visitor,{"scheme":"https"}), (Accept,_/_), (User-Agent,GitHub-Hookshot/21f57ba), (X-GitHub-Event,ping), (X-GitHub-Delivery,566f8a80-c50f-11e5-9fd7-26a70317acbf), (content-type,application/json), (Via,1.1 cloudflare), (CF-Connecting-IP,192.30.252.46))
[debug] application - BODY: {"zen":"Avoid administrative distraction.","hook_id":7086882,"hook":{"url":"https://api.github.com/repos/vijaykanthm28/java-spring-petclinic/hooks/7086882","test_url":"https://api.github.com/repos/vijaykanthm28/java-spring-petclinic/hooks/7086882/test","ping_url":"https://api.github.com/repos/vijaykanthm28/java-spring-petclinic/hooks/7086882/pings","id":7086882,"name":"web","active":true,"events":["push"],"config":{"content_type":"json","url":"https://api.megam.io/v2/assembly/upgrade/ASM1304160728042831872"},"last_response":{"code":null,"status":"unused","message":null},"updated_at":"2016-01-27T16:02:17Z","created_at":"2016-01-27T16:02:17Z"},"repository":{"id":48028002,"name":"java-spring-petclinic","full_name":"vijaykanthm28/java-spring-petclinic","owner":{"login":"vijaykanthm28","id":13815978,"avatar_url":"https://avatars.githubusercontent.com/u/13815978?v=3","gravatar_id":"","url":"https://api.github.com/users/vijaykanthm28","html_url":"https://github.com/vijaykanthm28","followers_url":"https://api.github.com/users/vijaykanthm28/followers","following_url":"https://api.github.com/users/vijaykanthm28/following{/other_user}","gists_url":"https://api.github.com/users/vijaykanthm28/gists{/gist_id}","starred_url":"https://api.github.com/users/vijaykanthm28/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/vijaykanthm28/subscriptions","organizations_url":"https://api.github.com/users/vijaykanthm28/orgs","repos_url":"https://api.github.com/users/vijaykanthm28/repos","events_url":"https://api.github.com/users/vijaykanthm28/events{/privacy}","received_events_url":"https://api.github.com/users/vijaykanthm28/received_events","type":"User","site_admin":false},"private":false,"html_url":"https://github.com/vijaykanthm28/java-spring-petclinic","description":"A sample Spring-based application","fork":true,"url":"https://api.github.com/repos/vijaykanthm28/java-spring-petclinic","forks_url":"https://api.github.com/repos/vijaykanthm28/java-spring-petclinic/forks","keys_url":"https://api.github.com/repos/vijaykanthm28/java-spring-petclinic/keys{/key_id}","collaborators_url":"https://api.github.com/repos/vijaykanthm28/java-spring-petclinic/collaborators{/collaborator}","teams_url":"https://api.github.com/repos/vijaykanthm28/java-spring-petclinic/teams","hooks_url":"https://api.github.com/repos/vijaykanthm28/java-spring-petclinic/hooks","issue_events_url":"https://api.github.com/repos/vijaykanthm28/java-spring-petclinic/issues/events{/number}","events_url":"https://api.github.com/repos/vijaykanthm28/java-spring-petclinic/events","assignees_url":"https://api.github.com/repos/vijaykanthm28/java-spring-petclinic/assignees{/user}","branches_url":"https://api.github.com/repos/vijaykanthm28/java-spring-petclinic/branches{/branch}","tags_url":"https://api.github.com/repos/vijaykanthm28/java-spring-petclinic/tags","blobs_url":"https://api.github.com/repos/vijaykanthm28/java-spring-petclinic/git/blobs{/sha}","git_tags_url":"https://api.github.com/repos/vijaykanthm28/java-spring-petclinic/git/tags{/sha}","git_refs_url":"https://api.github.com/repos/vijaykanthm28/java-spring-petclinic/git/refs{/sha}","trees_url":"https://api.github.com/repos/vijaykanthm28/java-spring-petclinic/git/trees{/sha}","statuses_url":"https://api.github.com/repos/vijaykanthm28/java-spring-petclinic/statuses/{sha}","languages_url":"https://api.github.com/repos/vijaykanthm28/java-spring-petclinic/languages","stargazers_url":"https://api.github.com/repos/vijaykanthm28/java-spring-petclinic/stargazers","contributors_url":"https://api.github.com/repos/vijaykanthm28/java-spring-petclinic/contributors","subscribers_url":"https://api.github.com/repos/vijaykanthm28/java-spring-petclinic/subscribers","subscription_url":"https://api.github.com/repos/vijaykanthm28/java-spring-petclinic/subscription","commits_url":"https://api.github.com/repos/vijaykanthm28/java-spring-petclinic/commits{/sha}","git_commits_url":"https://api.github.com/repos/vijaykanthm28/java-spring-petclinic/git/commits{/sha}","comments_url":"https://api.github.com/repos/vijaykanthm28/java-spring-petclinic/comments{/number}","issue_comment_url":"https://api.github.com/repos/vijaykanthm28/java-spring-petclinic/issues/comments{/number}","contents_url":"https://api.github.com/repos/vijaykanthm28/java-spring-petclinic/contents/{+path}","compare_url":"https://api.github.com/repos/vijaykanthm28/java-spring-petclinic/compare/{base}...{head}","merges_url":"https://api.github.com/repos/vijaykanthm28/java-spring-petclinic/merges","archive_url":"https://api.github.com/repos/vijaykanthm28/java-spring-petclinic/{archive_format}{/ref}","downloads_url":"https://api.github.com/repos/vijaykanthm28/java-spring-petclinic/downloads","issues_url":"https://api.github.com/repos/vijaykanthm28/java-spring-petclinic/issues{/number}","pulls_url":"https://api.github.com/repos/vijaykanthm28/java-spring-petclinic/pulls{/number}","milestones_url":"https://api.github.com/repos/vijaykanthm28/java-spring-petclinic/milestones{/number}","notifications_url":"https://api.github.com/repos/vijaykanthm28/java-spring-petclinic/notifications{?since,all,participating}","labels_url":"https://api.github.com/repos/vijaykanthm28/java-spring-petclinic/labels{/name}","releases_url":"https://api.github.com/repos/vijaykanthm28/java-spring-petclinic/releases{/id}","deployments_url":"https://api.github.com/repos/vijaykanthm28/java-spring-petclinic/deployments","created_at":"2015-12-15T07:54:00Z","updated_at":"2016-01-11T11:10:51Z","pushed_at":"2016-01-11T14:09:45Z","git_url":"git://github.com/vijaykanthm28/java-spring-petclinic.git","ssh_url":"git@github.com:vijaykanthm28/java-spring-petclinic.git","clone_url":"https://github.com/vijaykanthm28/java-spring-petclinic.git","svn_url":"https://github.com/vijaykanthm28/java-spring-petclinic","homepage":"","size":899,"stargazers_count":0,"watchers_count":0,"language":"Java","has_issues":false,"has_downloads":true,"has_wiki":true,"has_pages":false,"forks_count":0,"mirror_url":null,"open_issues_count":0,"forks":0,"open_issues":0,"watchers":0,"default_branch":"master"},"sender":{"login":"vijaykanthm28","id":13815978,"avatar_url":"https://avatars.githubusercontent.com/u/13815978?v=3","gravatar_id":"","url":"https://api.github.com/users/vijaykanthm28","html_url":"https://github.com/vijaykanthm28","followers_url":"https://api.github.com/users/vijaykanthm28/followers","following_url":"https://api.github.com/users/vijaykanthm28/following{/other_user}","gists_url":"https://api.github.com/users/vijaykanthm28/gists{/gist_id}","starred_url":"https://api.github.com/users/vijaykanthm28/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/vijaykanthm28/subscriptions","organizations_url":"https://api.github.com/users/vijaykanthm28/orgs","repos_url":"https://api.github.com/users/vijaykanthm28/repos","events_url":"https://api.github.com/users/vijaykanthm28/events{/privacy}","received_events_url":"https://api.github.com/users/vijaykanthm28/received_events","type":"User","site_admin":false}}

[error] p.c.s.n.PlayDefaultUpstreamHandler - Cannot invoke the action
java.util.NoSuchElementException: None.get
    at scala.None$.get(Option.scala:347) ~[org.scala-lang.scala-library-2.11.7.jar:na]
    at scala.None$.get(Option.scala:345) ~[org.scala-lang.scala-library-2.11.7.jar:na]
    at controllers.funnel.FunnelRequestBuilder.funneled(FunnelRequest.scala:105) ~[Megam%20Systems.megamgateway-0.9-sans-externalized.jar:na]
    at controllers.stack.SecurityActions$.Authenticated(SecurityActions.scala:48) ~[Megam%20Systems.megamgateway-0.9-sans-externalized.jar:na]
    at controllers.stack.APIAuthElement$class.proceed(APIAuthElement.scala:54) ~[Megam%20Systems.megamgateway-0.9-sans-externalized.jar:na]
    at controllers.camp.Assembly$.proceed(Assembly.scala:29) ~[Megam%20Systems.megamgateway-0.9-sans-externalized.jar:na]
    at jp.t2v.lab.play2.stackc.StackableController$StackActionBuilder.invokeBlock(StackableController.scala:16) ~[jp.t2v.stackable-controller_2.11-0.5.0.jar:0.5.0]
    at jp.t2v.lab.play2.stackc.StackableController$StackActionBuilder.invokeBlock(StackableController.scala:12) ~[jp.t2v.stackable-controller_2.11-0.5.0.jar:0.5.0]
    at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:493) ~[com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
    at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
