### ISSUE TITLE
sometimes gateway to scylladb connection got this error 

### ISSUE THREAD

**Issue by rajthilakmca** [megamsys/megam_gateway#333]
play.api.UnexpectedException: Unexpected exception[ExceptionInInitializerError: null]
    at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:169) ~[play-server_2.11-2.4.6.jar:2.4.6]
    at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:121) ~[play-server_2.11-2.4.6.jar:2.4.6]
    at scala.Option.map(Option.scala:146) ~[scala-library-2.11.7.jar:na]
    at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:121) ~[play-server_2.11-2.4.6.jar:2.4.6]
    at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:119) ~[play-server_2.11-2.4.6.jar:2.4.6]
    at scala.util.Success.flatMap(Try.scala:231) ~[scala-library-2.11.7.jar:na]
    at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:119) ~[play-server_2.11-2.4.6.jar:2.4.6]
    at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:111) ~[play-server_2.11-2.4.6.jar:2.4.6]
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.7.jar:na]
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.7.jar:na]
Caused by: java.lang.ExceptionInInitializerError: null
    at db.ScyllaConnector$class.$init$(ScyllaConnector.scala:15) ~[na:na]
    at db.scyllaConnection$.<init>(ScyllaConnector.scala:34) ~[na:na]
    at db.scyllaConnection$.<clinit>(ScyllaConnector.scala) ~[na:na]
    at models.base.ConcreteAccounts.space(Accounts.scala:98) ~[na:na]
    at models.base.ConcreteAccounts.insertNewRecord(Accounts.scala:102) ~[na:na]
    at models.base.Accounts$.models$base$Accounts$$$anonfun$31(Accounts.scala:175) ~[na:na]
    at models.base.Accounts$lambda$$$nestedInAnonfun$30$1.apply(Accounts.scala:174) ~[na:na]
    at models.base.Accounts$lambda$$$nestedInAnonfun$30$1.apply(Accounts.scala:174) ~[na:na]
    at scalaz.ValidationFlatMap.flatMap(Validation.scala:433) ~[scalaz-core_2.11-7.1.6.jar:na]
    at models.base.Accounts$.models$base$Accounts$$$anonfun$30(Accounts.scala:174) ~[na:na]
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /103.56.92.24:9042 (com.datastax.driver.core.OperationTimedOutException: [/103.56.92.24:9042] Operation timed out))
    at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:220) ~[cassandra-driver-core-3.0.0-alpha4.jar:na]
    at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:79) ~[cassandra-driver-core-3.0.0-alpha4.jar:na]
    at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1399) ~[cassandra-driver-core-3.0.0-alpha4.jar:na]
    at com.datastax.driver.core.Cluster.init(Cluster.java:162) ~[cassandra-driver-core-3.0.0-alpha4.jar:na]
    at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:341) ~[cassandra-driver-core-3.0.0-alpha4.jar:na]
    at com.datastax.driver.core.Cluster.connect(Cluster.java:286) ~[cassandra-driver-core-3.0.0-alpha4.jar:na]
    at db.Connector$.<init>(ScyllaConnector.scala:31) ~[na:na]
    at db.Connector$.<clinit>(ScyllaConnector.scala) ~[na:na]
    at db.ScyllaConnector$class.$init$(ScyllaConnector.scala:15) ~[na:na]
    at db.scyllaConnection$.<init>(ScyllaConnector.scala:34) ~[na:na]

**Comment by rajthilakmca** [comment]
found this 
megam network - error occurred
megam oja - its running

**Comment by indykish** [comment]
latency problem. hence closing it.
